application: petroms-sd
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: js  

- url: /css
  static_dir: css  

- url: /games
  static_dir: games  

- url: /img
  static_dir: img 
  
- url: /.*
  script: main.application
